import BiasDetection.BiasDetectionMetrics as BiasDetectionMetrics



# print('---------GPT2---------')
# causalObj = BiasDetectionMetrics.CausalLMBiasDetection(model_class='gpt2')

# print('---------Hellinger Distance---------')
# causalObj.hellingerDistance()
# print()
# print()
# print()
# print()
# print()
# print('---------Tok K Overlap(gender)---------')
# causalObj.topKOverlap(bias_type='gender')
# print()
# print()
# print()
# print()
# print()
# print('---------WeatScore(Gender)---------')
# causalObj.WeatScore(bias_type='gender')
# print()
# print()
# print()
# print()
# print()
# print('---------StereoScore(all)---------')
# causalObj.stereoSetScore(bias_type='all')
# print()
# print()
# print()
# print()
# print()
# print('---------Top K Percentage---------')
# causalObj.topKPercentage()
# print()
# print()
# print()
# print()
# print()
# print('---------Log Probability(Religion)---------')
# causalObj.logProbability(bias_type='religion')
# print()
# print()
# print()
# print()
# print()


print('---------Bert---------')
maskedObj = BiasDetectionMetrics.MaskedLMBiasDetection(model_class='bert-base-uncased')
print('---------Log Probability---------')
maskedObj.logProbability(bias_type='gender')
print()
print()
print()
print()
print()
print('---------F1 Score---------')
maskedObj.F1Score(bias_type='gender')
print()
print()
print()
print()
print()
print('---------StereoScore(all)---------')
maskedObj.stereoSetScore(bias_type='all')
print()
print()
print()
print()
print()
print('---------Top K Percentage---------')
maskedObj.topKPercentage()
print()
print()
print()
print()
print()
print('---------WeatScore(Health)---------')
maskedObj.WeatScore(bias_type='health')

