import BiasDetection.BiasDetectionMetrics as BiasDetectionMetrics
from transformers import AutoModel
from transformers import AutoTokenizer, BioGptTokenizer,BertForMaskedLM
from transformers import AutoTokenizer, GPT2LMHeadModel


def masked_model_metrics(model_name):
    print('---------'+model_name+'---------')

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = BertForMaskedLM.from_pretrained(model_name)
    maskedObj = BiasDetectionMetrics.MaskedLMBiasDetection(use_pretrained=False, model = model, tokenizer = tokenizer)

    print('---------Log Probability(gender)---------')
    maskedObj.logProbability(bias_type='gender')
    print('---------Log Probability(religion)---------')
    maskedObj.logProbability(bias_type='religion')
    print('---------Log Probability(Race)---------')
    maskedObj.logProbability(bias_type='race')
    print()
    print()
    print()
    print()
    print()
    print('---------F1 Score---------')
    maskedObj.F1Score(bias_type='gender')
    print()
    print()
    print()
    print()
    print()
    print('---------StereoScore(all)---------')
    maskedObj.stereoSetScore(bias_type='all')
    print()
    print()
    print()
    print()
    print()
    print('---------Top K Percentage---------')
    maskedObj.topKPercentage()
    print()
    print()
    print()
    print()
    print()
    print('---------WeatScore(Health)---------')
    maskedObj.WeatScore(bias_type='health')
    print('---------WeatScore(Age)---------')
    maskedObj.WeatScore(bias_type='age')
    print('---------WeatScore(Gender)---------')
    maskedObj.WeatScore(bias_type='gender')
    print('---------WeatScore(Race)---------')
    maskedObj.WeatScore(bias_type='race')
    print('---------WeatScore(Religion)---------')
    maskedObj.WeatScore(bias_type='religion')
    print('')
    print()
    print()
    print()
    print()
    print()
    print('---------HellingerDistance(Gender)---------')
    maskedObj.hellingerDistance()



def causal_model_metrics(model_name):
    print('---------'+model_name+'---------')

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = GPT2LMHeadModel.from_pretrained(model_name).to('mps')
    causalObj = BiasDetectionMetrics.CausalLMBiasDetection(use_pretrained=False, model = model, tokenizer = tokenizer)

    # print('---------Hellinger Distance---------')
    # causalObj.hellingerDistance()
    # print()
    # print()
    # print()
    # print()
    # print()
    # print('---------Tok K Overlap(gender)---------')
    # causalObj.topKOverlap(bias_type='gender')
    print()
    print()
    print()
    print()
    print()
    print('---------WeatScore(Gender)---------')
    causalObj.WeatScore(bias_type='gender')
    print()
    print()
    print()
    print()
    print()
    print('---------StereoScore(all)---------')
    causalObj.stereoSetScore(bias_type='all')
    print()
    print()
    print()
    print()
    print()
    print('---------Top K Percentage---------')
    causalObj.topKPercentage()
    print()
    print()
    print()
    print()
    print()
    print('---------Log Probability(Religion)---------')
    causalObj.logProbability(bias_type='religion')
    print()
    print()
    print()
    print()
    print()



# masked_model_metrics("emilyalsentzer/Bio_ClinicalBERT")
# masked_model_metrics("emilyalsentzer/Bio_Discharge_Summary_BERT")
# masked_model_metrics("microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract")
masked_model_metrics("microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext")
# causal_model_metrics("microsoft/biogpt")